### ISSUE TITLE
Help threejs logic

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uojs2#86]
Can you help me? I described here https://github.com/kevinhikaruevans/uojs2/blob/threejs-native/test.html threejs logic but missed something and can not find the error.

**Comment by kevinhikaruevans** [comment]
It's working for me. Small square with texture appears.

Few minor things:

- Should use PlaneGeometry instead of PlaneBufferGeometry
- Only one camera object should be used. It looks like when you call camera(), it makes a new camera each time. 
- Position (on tile) is not being used
- Consider using requestAnimationFrame and loop through `renderer.render( scene, camera );`

**Comment by lamo2k123** [comment]
all tiles are drawn at one point

**Comment by kevinhikaruevans** [comment]
Position isn't being set on the tiles.

**Comment by lamo2k123** [comment]
hmm vertices incorrectly work :( https://github.com/kevinhikaruevans/uojs2/blob/threejs-native/test.html#L82

**Comment by ghost-458** [comment]
Not sure. You might need to post it on stackoverflow or something
